name: CI usando workflow reusable

on:
  schedule:
    - cron: "41 22 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Este paso solo crea un archivo de ejemplo, sin npm
      - name: Crear artefacto de prueba
        run: |
          mkdir -p output
          echo "Esto es 15 de diciembre 2025" > output/hello.txt

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: prueba-artifact
          path: output
          if-no-files-found: warn
