name: ConexiÃ³n a Vault

on:
  push:
    branches: [connection-hashicorp]

jobs:
  vault:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Vault via AppRole
        id: vault-login
        run: |
          TOKEN=$(docker exec -e VAULT_ADDR=http://127.0.0.1:8200 vault \
            vault write -field=token auth/approle/login \
            role_id=${{ secrets.VAULT_ROLE_ID }} \
            secret_id=${{ secrets.VAULT_SECRET_ID }})
          echo "VAULT_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Read secret from Vault
        run: |
          # Leer el secret completo en JSON
          SECRET_JSON=$(docker exec -e VAULT_ADDR=http://127.0.0.1:8200 -e VAULT_TOKEN=$VAULT_TOKEN vault \
            vault kv get -format=json secret/australia)
      
          # Extraer username y password
          USERNAME=$(echo $SECRET_JSON | jq -r '.data.data.username')
          PASSWORD=$(echo $SECRET_JSON | jq -r '.data.data.password')
      
          # Exportar variables para otros pasos
          echo "APP_USER=$USERNAME" >> $GITHUB_ENV
          echo "APP_PASS=$PASSWORD" >> $GITHUB_ENV

