name: Action cada 5 minutos

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  ejecutar-tarea:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Esta acci√≥n se ejecuta cada 5 minutos"
