name: CI usando workflow reusable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ejecutar-reusable:
    uses: ricardops2211/orquestador-github/.github/workflows/orquestacion-cert.yml@reusbale-repo
    with:
      node-version: '18'
      entorno: 'producci√≥n'
