name: Generate Workflow Report

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "pablo-1712" ]

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Obtener ejecuciones de GitHub Actions
        run: ./get_runs.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_FULL: ${{ github.repository }}

      - name: Procesar ejecuciones y generar CSV
        run: python3 parse_runs.py

      - name: Subir CSV como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: workflow-runs-report
          path: runs_report.csv
