name: ConexiÃ³n a Vaults

on:
  push:
    branches: [connection-hashicorp]

jobs:
  vault:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Vault via AppRole
        id: vault-login
        run: |
          TOKEN=$(docker exec -e VAULT_ADDR=http://127.0.0.1:8200 vault \
            vault write -field=token auth/approle/login \
            role_id=${{ secrets.VAULT_ROLE_ID }} \
            secret_id=${{ secrets.VAULT_SECRET_ID }})
          echo "VAULT_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Read secret australia from Vault
        run: |
          APP_USER=$(docker exec -e VAULT_ADDR=http://127.0.0.1:8200 -e VAULT_TOKEN=$VAULT_TOKEN vault \
            vault kv get -field=username secret/australia)
          
          APP_PASS=$(docker exec -e VAULT_ADDR=http://127.0.0.1:8200 -e VAULT_TOKEN=$VAULT_TOKEN vault \
            vault kv get -field=password secret/australia)

          echo "APP_USER=$APP_USER" >> $GITHUB_ENV
          echo "APP_PASS=$APP_PASS" >> $GITHUB_ENV

      - name: Use secrets
        run: |
          echo "Usuario: $APP_USER"
          echo "Password length: ${#APP_PASS}"
