name: ConexiÃ³n a vault

on:
  push:
    branches: [connection-hashicorp]

jobs:
  vault:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Vault via AppRole
        id: vault-login
        run: |
          TOKEN=$(docker exec -e VAULT_ADDR=http://127.0.0.1:8200 vault \
            vault write -field=token auth/approle/login \
            role_id=${{ secrets.VAULT_ROLE_ID }} \
            secret_id=${{ secrets.VAULT_SECRET_ID }})
          echo "VAULT_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Read secret from Vault
        run: |
          USER=$(docker exec -e VAULT_ADDR=http://127.0.0.1:8200 -e VAULT_TOKEN=$VAULT_TOKEN vault \
            vault kv get -field=username secret/apiNavidad)
          PASS=$(docker exec -e VAULT_ADDR=http://127.0.0.1:8200 -e VAULT_TOKEN=$VAULT_TOKEN vault \
            vault kv get -field=password secret/apiNavidad)
          echo "APP_USER=$USER" >> $GITHUB_ENV
          echo "APP_PASS=$PASS" >> $GITHUB_ENV

      - name: Use secret
        run: |
          echo "Usuario: $APP_USER"
          echo "Password length: ${#APP_PASS}"

          echo "APP_PASS=$PASS" >> $GITHUB_ENV
